### PR TITLE
Add installation from a fixed conda environment

### PR DESCRIPTION
**Pull request by marinegor**
Hi, I noticed that I can not fully reproduce the installation now, and thus submitted a PR that adds a fixed `careless.yml` file with versions of **all** packages specified, and a respective lines in the README.md.

What will happen if I simply install `careless` with conda:

```
conda create -n careless python==3.8 # doesn't work with 3.7 either
conda activate careless
python3 -m pip install -e .
```

And then, if I run the `thermolysin_xfel` example, I get:

```
(careless_fail) marinegor@marin-desktop:~/github/careless-examples/thermolysin_xfel_test$ bash merge.sh 
Traceback (most recent call last):
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/bin/careless", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/marinegor/github/careless/careless/careless", line 72, in <module>
    merger = MonoMerger.from_mtzs(
  File "/home/marinegor/github/careless/careless/merge/merge.py", line 120, in from_mtzs
    return cls(loader(), anomalous, **kwargs)
  File "/home/marinegor/github/careless/careless/merge/merge.py", line 78, in __init__
    ds.loc[:,['H', 'K', 'L']] = friedel_sign[:,None] * ds.loc[:,['H', 'K', 'L']]
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/generic.py", line 1935, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/arraylike.py", line 250, in array_ufunc
    result = maybe_dispatch_ufunc_to_dunder_op(self, ufunc, method, *inputs, **kwargs)
  File "pandas/_libs/ops_dispatch.pyx", line 91, in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/arraylike.py", line 109, in __rmul__
    return self._arith_method(other, roperator.rmul)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/frame.py", line 5979, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/frame.py", line 6015, in _dispatch_frame_op
    bm = self._mgr.operate_blockwise(right._mgr, array_op)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 374, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/internals/ops.py", line 54, in operate_blockwise
    res_values = array_op(lvals, rvals)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 185, in arithmetic_op
    res_values = op(lvalues, rvalues)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/ops/roperator.py", line 17, in rmul
    return right * left
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/arrays/integer.py", line 387, in __array_ufunc__
    result = ops.maybe_dispatch_ufunc_to_dunder_op(
  File "pandas/_libs/ops_dispatch.pyx", line 91, in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/arraylike.py", line 109, in __rmul__
    return self._arith_method(other, roperator.rmul)
  File "/home/marinegor/apps/anaconda3/envs/careless_fail/lib/python3.8/site-packages/pandas/core/arrays/numeric.py", line 44, in _arith_method
    raise TypeError("can only perform ops with numeric values")
TypeError: can only perform ops with numeric values
```

I asked my colleague who had a working copy of `careless` approximately when the preprint came out to make an `careless.yml` file with:

`conda env export > careless.yml`

and send it to me -- and this is exactly the file I'm adding in this PR.

For comparison, the not-working `careless.yml` file is attached.

[careless_fail.zip](https://github.com/Hekstra-Lab/careless/files/5973835/careless_fail.zip)

### CODE REVIEW

**Comment by JBGreisman** [comment]
Hey -- that error message is something I debugged recently, and the culprit is actually `pandas`. There's a line in `merge.py` that stopped working with the recent versions of `pandas` (>1.2.1). It can be resolved by downgrading solely `pandas` to 1.1.4.

More practically though, I made a small change in the `experimental` branch that resolves this issue for the latest `pandas` versions. @kmdalton told me he's planning to merge those into the main branch shortly

**Comment by JBGreisman** [comment]
Looking through the environment versions you made here, I have a hunch the only operative one is that `pandas. 1.1.5` is used.

**Comment by kmdalton** [comment]
yes! @JBGreisman is helping put together a pull request to fix this issue. we should be able to resolve this this afternoon.

**Comment by marinegor** [comment]
Ok, I see, pandas is the problem indeed.

Generally, having a `requirements.txt` with strictly defined versions is a cheap way for the more reproducible builds even without much CI. Since the disk space is (usually) not the limitation for such projects, completely duplicating most of the packages works fine.

But I'm fine with either option, obviously!

**Comment by kmdalton** [comment]
@marinegor, I'd like to maintain as much flexibility in terms of versioning as possible. The `TensorFlow` devs are constantly adding new features that impact model training speed. So, I think it behooves us to keep the installation scripts as vague as reasonably attainable. That being said, the `main` branch should be working for you again. Please let me know when you can confirm that, and I'll close this issue. 

Thanks!

**Comment by marinegor** [comment]
@kmdalton yep, everything works with the current main, feel free to close that.

**Comment by kmdalton** [comment]
awesome sounds good!

**Pull request closed without merging**
